# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.user_manager:
        class: AppBundle\Backend\Users\UserManager
        arguments: ["@pmanager"]

    pmanager:
        class: AppBundle\Service\PommManager
        arguments: ["@pomm"]

    app.response_listener:
        class: AppBundle\EventListener\Kernel\ResponseListener
        tags:
              - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
