# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.user_manager:
        class: AppBundle\Backend\Users\UserManager
        arguments: ["@pmanager"]

    converter:
        class: AppBundle\Service\FormatConverter

    esmanager:
        class: AppBundle\Service\ESManager
        arguments: ["@m6web_elasticsearch.client.default"]

    pmanager:
        class: AppBundle\Service\PommManager
        arguments: ["@pomm"]