<?php
/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace AppBundle\Model\Caldav\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Calendars
 *
 * Structure class for relation public.calendars.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Calendars extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.calendars')
            ->setPrimaryKey([])
            ->addField('uid', 'int4')
            ->addField('principaluri', 'text')
            ->addField('displayname', 'text')
            ->addField('uri', 'text')
            ->addField('synctoken', 'int4')
            ->addField('description', 'text')
            ->addField('calendarorder', 'int4')
            ->addField('calendarcolor', 'text')
            ->addField('timezone', 'text')
            ->addField('components', 'text[]')
            ->addField('transparent', 'int4')
            ;
    }
}
