
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

test:
    path:     /test
    defaults: { _controller: AppBundle:Default:test }

caldav:
    path:     /caldav/{url}
    defaults: { _controller: AppBundle:CalDAV:index, url: null }
    requirements:
        url: ".*"
