
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

test:
    path:     /test
    defaults: { _controller: AppBundle:Default:test }

caldav:
    path:     /caldav/{url}
    defaults: { _controller: AppBundle:CalDAV:index, url: null }
    requirements:
        url: ".*"

api:
    resource: "@AppBundle/Resources/config/APIrouting.yml"
    prefix:   /api


event_home:
    path:     /event/
    defaults: { _controller: AppBundle:Browser:eventHome }

event_create:
    path:     /event/create
    defaults: { _controller: AppBundle:Browser:eventCreate }

event_read:
    path:     /event/{uri}
    defaults: { _controller: AppBundle:Browser:eventRead }

event_update:
    path:     /event/{uri}/edit
    defaults: { _controller: AppBundle:Browser:eventUpdate }

event_delete: 
    path:     /event/{uri}/delete
    defaults: { _controller: AppBundle:Browser:eventDelete }


calendar_home:
    path:     /calendar/
    defaults: { _controller: AppBundle:Browser:calendarHome }

calendar_create:
    path:     /calendar/create
    defaults: { _controller: AppBundle:Browser:calendarCreate }

calendar_read:
    path:     /calendar/{uri}
    defaults: { _controller: AppBundle:Browser:calendarRead }

calendar_update:
    path:     /calendar/{uri}/edit
    defaults: { _controller: AppBundle:Browser:calendarUpdate }

calendar_delete:
    path:     /calendar/{uri}/delete
    defaults: { _controller: AppBundle:Browser:calendarDelete }