<?php
/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace AppBundle\Model\Ode\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Calendarchange
 *
 * Structure class for relation public.calendarchange.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Calendarchange extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.calendarchange')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('uri', 'text')
            ->addField('synctoken', 'int4')
            ->addField('calendarid', 'int4')
            ->addField('operation', 'int4')
            ;
    }
}
