<?php

/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */
namespace AppBundle\Model\Ode\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Principal.
 *
 * Structure class for relation public.principal.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 *
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 * @see RowStructure
 */
class Principal extends RowStructure
{
    /**
     * __construct.
     *
     * Structure definition.
     */
    public function __construct()
    {
        $this
            ->setRelation('public.principal')
            ->setPrimaryKey([])
            ->addField('id', 'int4')
            ->addField('uri', 'text')
            ->addField('email', 'text')
            ->addField('displayname', 'text')
            ->addField('vcardurl', 'text')
            ;
    }
}
