<?php

/**
 * This file has been automaticaly generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */
namespace AppBundle\Model\Ode\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Users.
 *
 * Structure class for relation public.users.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 *
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 * @see RowStructure
 */
class Users extends RowStructure
{
    /**
     * __construct.
     *
     * Structure definition.
     */
    public function __construct()
    {
        $this
            ->setRelation('public.users')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('username', 'text')
            ->addField('username_canonical', 'text')
            ->addField('email', 'text')
            ->addField('email_canonical', 'text')
            ->addField('salt', 'text')
            ->addField('password', 'text')
            ->addField('password_digesta', 'text')
            ->addField('locked', 'bool')
            ->addField('expired', 'bool')
            ->addField('expires_at', 'text')
            ->addField('confirmation_token', 'text')
            ->addField('password_requested_at', 'text')
            ->addField('roles', 'text[]')
            ->addField('credentials_expired', 'bool')
            ->addField('credentials_expire_at', 'text')
            ->addField('enabled', 'bool')
            ->addField('last_login', 'timestamp')
            ;
    }
}
