-- Role: ODE

DROP ROLE "ODE";

CREATE ROLE "ODE" LOGIN
  --ENCRYPTED PASSWORD 'md5f7111bdf18441ad5c02441cba1aa5c1e'
  PASSWORD 'ODEPASSWORD'
  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

